### ISSUE TITLE
what is the preferred method of upgrading versions, say 2.3.4 to 2.3.5 on ubuntu ?

### ISSUE THREAD

**Issue by solarfox22** [trackmastersteve/alienfx#102]
### 1. Expected behavior.

-

### 2. Actual behavior.

-

### 3. Steps to reproduce the problem.

-

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version:
- Operating System:
- Hardware Version:

**Comment by trackmastersteve** [comment]
You should be able to just install on top of previous versions. The files will be overwritten.
