### ISSUE TITLE
Uninstall on pop os

### ISSUE THREAD

**Issue by V1K1NGbg** [trackmastersteve/alienfx#111]
Can someone plese provide some detailed instructions for deinstalation?

Thank you in advance!

**Comment by JustCryen** [comment]
I'm not on PopOS so take it as you will but if there's no official deinstallation method for your disro, I'll provide folders & files that alienfx populated in my system (Arch Linux)
`/etc/udev/rules.d/10-alienfx.rules`
`/usr/bin/alienfx`
`/usr/bin/alienfx-gtk`
`/usr/lib/python3.10/site-packages/alienfx/`
`/usr/lib/python3.10/site-packages/alienfx-*`
`/usr/share/applications/alienfx.desktop`
`/usr/share/icons/hicolor/48x48/apps/alienfx.png`
`/usr/share/icons/hicolor/scalable/apps/alienfx.svg`
`/usr/share/man/man1/alienfx.1.gz`
`/usr/share/pixmaps/alienfx.png`
You really shouldn't delete these by hand but you can check if they're there before and after you tried to uninstall it.

**Actually**, I guess you can try to uninstall it with `pip uninstall alienfx`
