### ISSUE TITLE
13R3 Support

### ISSUE THREAD

**Issue by MrMEEE** [trackmastersteve/alienfx#16]
Hi

I'm trying to add support for Alienware 13 R3...

But after having created the controller and installed the modified version.. I get 

ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/alienfx/ui/gtkui/gtkui.py", line 212, in set_theme
    self.controller.set_theme(self.themefile)
  File "build/bdist.linux-x86_64/egg/alienfx/core/controller.py", line 259, in set_theme
    self._wait_controller_ready()
  File "build/bdist.linux-x86_64/egg/alienfx/core/controller.py", line 143, in _wait_controller_ready
    ready = (resp[0] == self.cmd_packet.STATUS_READY)
TypeError: 'NoneType' object has no attribute '__getitem__'

when trying to apply a profile from alienfx-gtk...

I guess some of the parameters in the controller is off.. but how do I figure out what to enter???

Regards

Martin

lsusb -v -s 001:002

Bus 001 Device 002: ID 187c:0529 Alienware Corporation 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               0.02
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x187c Alienware Corporation
  idProduct          0x0529 
  bcdDevice            0.00
  iManufacturer           1 Alienware
  iProduct                2 AW13
  iSerial                 3 03.00
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      56
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)

**Comment by trackmastersteve** [comment]
Hi Martin,

I have a couple questions to try and help figure out whats wrong. Did you use sudo to install the app? Also, what version(s) of python do you have installed?

**Comment by trackmastersteve** [comment]
Can you let me know what modifications you made for the m13r3 as well?

**Comment by MrMEEE** [comment]
I'll do a PR with the changes I made

**Comment by MrMEEE** [comment]
and yes, I used sudo

**Comment by MrMEEE** [comment]
/usr/local/lib/python2.7/dist-packages/alienfx-2.0.5-py2.7.egg/alienfx/ui/gtkui/gtkui.py:37: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.

(alienfx-gtk:23034): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(alienfx-gtk:23034): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(alienfx-gtk:23034): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
ERROR:root:Cant detach kernel driver. Error : Entity not found
ERROR:root:Cant set configuration. Error : Resource busy
ERROR:root:Cant claim interface. Error : Resource busy
ERROR:root:write_packet: [Errno 16] Resource busy
ERROR:root:read_packet: [Errno 16] Resource busy
ERROR:root:write_packet: [Errno 16] Resource busy
ERROR:root:write_packet: [Errno 16] Resource busy
ERROR:root:read_packet: [Errno 16] Resource busy
ERROR:root:Cant re-attach. Error : Resource busy
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/alienfx/ui/gtkui/gtkui.py", line 212, in set_theme
    self.controller.set_theme(self.themefile)
  File "build/bdist.linux-x86_64/egg/alienfx/core/controller.py", line 259, in set_theme
    self._wait_controller_ready()
  File "build/bdist.linux-x86_64/egg/alienfx/core/controller.py", line 143, in _wait_controller_ready
    ready = (resp[0] == self.cmd_packet.STATUS_READY)
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by MrMEEE** [comment]
Complete error above

**Comment by MrMEEE** [comment]
These are the errors with the changes that you committed...

**Comment by ochetski** [comment]
I'm trying to use with the same hardware, Aurora R3 and Python 2.7.12, trying on ubuntu nogui.
Not pro on python, but if you need any info about the hardware I'm happy to help.

**Comment by trackmastersteve** [comment]
This project was given to me and I'm still pretty new to python. I'm still in the learning process myself. I'm still in the process of working out those warnings about deprecated parts of gtk.

**Comment by trackmastersteve** [comment]
I'm also trying to figure out what is causing those errors.

**Comment by rahul95ram** [comment]
Hi guys, Im facing the same issue. I too have an alienware 13r3  and am unable to find a fix to controlling the keyboard backlighting.
Did you manage to fix the issue?
Is there another working solution for this requirement?

**Comment by miquelmassot** [comment]
I can find this information, but I have no clue on how to write it in the driver:
Name: Alienhead
GroupID: 5
ZoneID: 6, 15

Name: Touchpad
GroupID: 7, 
ZoneID: 8, 17

Name: Keyboard
GroupID: 1
ZoneID: 2, 11

Name: Keyboard
GroupID: 2
ZoneID: 3, 12

Name: Keyboard
GroupID: 3
ZoneID: 4, 13

Name: Keyboard
GroupID: 4
ZoneID: 5, 14

Name: Logo
GroupID: 6
ZoneID: 7, 16

Name: Power
GroupID: 8
ZoneID: 1, 9, 10, 18, 19, 20, 21, 22

**Comment by trackmastersteve** [comment]
You can compare those zone codes with the ones in: [https://github.com/trackmastersteve/alienfx/blob/master/alienfx/core/controller_m13xr3.py](url)

**Comment by trackmastersteve** [comment]
Feel free to make the necessary changes and submit a pull request.

**Comment by Gurjot95** [comment]
The new models since 13R3 needs 12 byte instruction to send to HID instead of the original 9. I have made the SDK which supports all alienware laptops.

https://github.com/Gurjot95/AlienFX-SDK/tree/master/AlienFX_SDK
