### ISSUE TITLE
13R3 - Error using GUI/cml - [Errno 75] Overflow ; [Errno 32] Pipe error ; 

### ISSUE THREAD

**Issue by rahul95ram** [trackmastersteve/alienfx#20]
I have been looking for a solution to control the alienware 13's keyboard back lighting. 
I simply want to have the functionality to turn it off and on. 
Having installed alienfx, I ran into some issues - 
This is the complete error message: 

/usr/local/lib/python2.7/dist-packages/alienfx-2.0.5-py2.7.egg/alienfx/ui/gtkui/gtkui.py:37: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/alienfx/ui/gtkui/gtkui.py", line 212, in set_theme
    self.controller.set_theme(self.themefile)
  File "build/bdist.linux-x86_64/egg/alienfx/core/controller.py", line 259, in set_theme
    self._wait_controller_ready()
  File "build/bdist.linux-x86_64/egg/alienfx/core/controller.py", line 143, in _wait_controller_ready
    ready = (resp[0] == self.cmd_packet.STATUS_READY)
TypeError: 'NoneType' object has no attribute '__getitem__'

HELP?

**Comment by Dutisto** [comment]
Hi, 

I actually have the same bug with my 13R3 =]

**Comment by roobytwo** [comment]
same issue

**Comment by rahul95ram** [comment]
Hi guys, I have found a fix. Although its more of a compromise than a fix. If you set all the lights to off in windows and save this as the active profile, the keyboard lighting settings are retained in Ubuntu.

**Comment by derco0n** [comment]
may be its the same as in the 17R4. the controller build in there need 8 bits per color instead of 4 so the messages are getting longer resulting in 12 instead of 9 bytes...

**Comment by ssteinberg** [comment]
Yes, we need 8-bits per pixel and 12-byte length messages. I have made a very quick fork that will work on the AW13R3, but will, obviously, break on older models. Feel free to try for now, but it will require a cleaner solution for integration upstream.

**Comment by derco0n** [comment]
i'm currently working on support for model 17R4. for that purpose i created a newcmdpacket.py with modified properties for newer alienfx-controllers. it is still under development, but you might have a look at my fork: [https://github.com/derco0n/alienfx](url)

**Comment by derco0n** [comment]
@ssteinberg @lorhm @roobytwo @Dutisto 
my work for the 17R4 is merged to the master branch.
I bet the 13R3 is using a newer controller as well.
I recommend you to sync the project to your machine and modify your controller_<device>.py in the way the controller_m17r4.py is built.

You may try the zonescanner to find some correct zone codes.

Please let us know if this works.
If you have a working controller-config for your device, please share.
Thank you in advance.

**Comment by StephanX** [comment]
@ssteinberg Thanks a bunch!  Your fork worked like a charm.
