### ISSUE TITLE
X51 Support

### ISSUE THREAD

**Issue by Tank-Missile** [trackmastersteve/alienfx#22]
I have tried to find the VID and PID for my Alienware X51 R2 through the lsusb command, but I don't think it uses USB for changing the light color.

**Comment by trackmastersteve** [comment]
The lsusb output should look something like this:
`Bus 004 Device 003: ID 187c:0512 Alienware Corporation`
which, in my case, would be `187c:0512`.

**Comment by Tank-Missile** [comment]
The command does not produce any buses that have "Alienware Corporation". There is one for my alienware keyboard, but none for the lights on the computer itself.

**Comment by trackmastersteve** [comment]
Wow, I hope they didn't change the way AlienFX lighting is implemented.

**Comment by Tank-Missile** [comment]
The model was produced back in 2013, so unlikely.

**Comment by imbellish** [comment]
@trackmastersteve @Tank-Missile I have an X51 R2 and can confirm they've moved from the USB model. However, there's a linux module, [alienware-wmi](https://github.com/torvalds/linux/blob/master/drivers/platform/x86/alienware-wmi.c) which can control the lights.

Following some advice in this [reddit post](https://reddit.com/r/AlienwareAlpha/comments/9j57ck/alienfx_hdmi_passthrough_control_for_linux/) leads to this bash script:

```
#!/bin/bash

exec >/dev/null
exec 2>/dev/null

platform_dir=/sys/devices/platform/alienware-wmi

if [ "$1" = "--query-led-presence" ]
then
  if [ -d "$platform_dir/rgb_zones" ]
  then
    exit 0
  else
    exit 1
  fi
fi

if [ "$1" = "--query-hdmi-mux-presence" ]
then
  if [ -d "$platform_dir/hdmi" ]
  then
    exit 0
  else
    exit 1
  fi
fi

if [ "$1" = "--query-hdmi-mux-cable-presence" ]
then
  if [ ! -d "$platform_dir/hdmi" ]
  then
    exit 1
  fi
  status=$(cat $platform_dir/hdmi/cable | sed 's,.*\[,,; s,\].*,,')
  if [ "$status" = "connected" ]
  then
    exit 0
  else
    exit 1
  fi
fi

if [ "$1" = "--hdmi-mux" ]
then
  if [ ! -d "$platform_dir/hdmi" ]
  then
    exit 1
  fi
  echo $2 > $platform_dir/hdmi/source
  exit 0
fi

if [ "$1" = "--led-brightness" ]
then
  if [ ! -f "$platform_dir/leds/alienware::global_brightness/brightness" ]
  then
    exit 1
  fi
  echo $2 > $platform_dir/leds/alienware\:\:global_brightness/brightness
  exit 0
fi

if [ "$1" = "head" ]; then
  zone="zone00"
elif [ "$1" = "left" ]; then
  zone="zone01"
elif [ "$1" = "right" ]; then
  zone="zone02"
fi

if [ ! -f "$platform_dir/rgb_zones/${zone}" ]
then
  exit 1
fi

R=0$(printf '%x\n' $2)
G=0$(printf '%x\n' $3)
B=0$(printf '%x\n' $4)
RGB="$R$G$B"

echo "running" > $platform_dir/rgb_zones/lighting_control_state
echo $RGB      > $platform_dir/rgb_zones/${zone}
```

Unfortunately it seems adding a controller for a non-USB interface doesn't seem like a trivial fix.
