### ISSUE TITLE
Area51 R4 Support

### ISSUE THREAD

**Issue by henricook** [trackmastersteve/alienfx#24]
Hi all,

I was excited to find this project, i'm sitting on an Alienware Area51 R4. I'm also a developer, so i don't mind getting my hands dirty - is anyone free to send me a message with a bit about the project layout and how to do things like find my model number so i can add support for it?

**Comment by trackmastersteve** [comment]
The info you're looking for is in the file [https://github.com/trackmastersteve/alienfx/blob/2.0.6/CONTRIBUTING.md](url). And Thank you for offering your support!

**Comment by trackmastersteve** [comment]
Also, I have plans to update some of the GTK code that will be deprecated. Which I'd be happy to accept by others. The structure of the two version numbers is as follows:

2.0.6 is the "Current Version" which you can push new Alienware versions to.
2.1.x is the "Beta Version" that I hope to push any other code to, like GTK code etc.

**Comment by trackmastersteve** [comment]
@henricook were you able to find anything about your Alienware model?

**Comment by henricook** [comment]
Sorry for not getting back to you!

My Area51 R4 model has the following VID and PID

 # USB VID and PID
        self.vendor_id = 0x187c
        self.product_id = 0x0526

I didn't get too much of a chance to play with the project alas, but hopefully that helps add the model? Please let me know if you need anything else at all!
