### ISSUE TITLE
15R1 Support

### ISSUE THREAD

**Issue by Witko** [trackmastersteve/alienfx#25]
Hi,
is the alienware 15 R1 supported?

**Comment by Witko** [comment]
Okay i found out that its not. Im able to set the colors though. Ahy hints how to figure out the mapping? Why does the HDD_LEDS behave differently than other zones? I can change those leds(wifi and caps as well) to any color if it was under different constant.

**Comment by trackmastersteve** [comment]
If you have windows installed you can run wireshark to see the zone codes as you change the colors. Another way I found is to try and Google for the zone codes, but it's very hard to find zone codes for every model and Alienware isn't very helpful with this either. Also, if the zones are just mixed up, you can just change the codes around to the correct order.

**Comment by Witko** [comment]
i did that just a moment ago - but tbh its hard for me to understand where the actual zone data is. I tried to capture 2 zones both blue and red colors - to see what is same a and what different but i really cant figure it out.
