### ISSUE TITLE
Create a Zone Scanner

### ISSUE THREAD

**Issue by trackmastersteve** [trackmastersteve/alienfx#27]
We need to create a "Zone Scanner" that will scan each zone code, one at a time. This will help people to add support for their Alienware models.

**Comment by Witko** [comment]
Im willing to help. Im not much skilled with python but you can fix my code on PR review:)

**Comment by derco0n** [comment]
@trackmastersteve how can i help?
Has the development of this component started yet?

I suggest a cli-based scanner which does the following:
Step 1: Searching for USB-devices with user given vendor-id and "0x187c" as default value
Step 2: Trying the following on every device found
Round 1: 
-Testing well known zones with blinking or lightning (We know they follow some pattern...)
-Asking user if anything happend
Round 2 (If not all codes were found):
-Testing all possible zone codes (yes, there could be very much of them)
-Asking user if anything happend
Step 3: Write the results to log- or even better a controller-definition

**Comment by Witko** [comment]
@derco0n ,
i've tried something like that some time ago - but the results were not very optimistic. A lot of changes were not tied to only one zone etc.

**Comment by trackmastersteve** [comment]
I haven't attempted this yet myself.

**Comment by derco0n** [comment]
I'll investigate the existing controller.py's to double check it, but for me it seems the base addresses for the zones are always doubling.
Every other address produces undefined behaviour like triggering multiple zone with random colors, blinking and so on.

If i can confirm that by reviewing the controllers, i'll try to build a prober...

**Comment by derco0n** [comment]
i have created a zone scanner which is working for me.
pull request incoming....
