### ISSUE TITLE
15R3 Support

### ISSUE THREAD

**Issue by akxer** [trackmastersteve/alienfx#30]
Tried to run it on my alienware 15 R3, the first error I got was 
`ImportError: No module named builtins` which I fixed by running `sudo pip install future`

Now it's running but, the theme is not applying(gets stuck at Applying theme).

**Comment by TheNetworker** [comment]
I have the same error also

**Comment by trackmastersteve** [comment]
I have added "pip install future" to the install process which fixes the Import Error. As far as getting stuck at "Applying Theme", are you still having the issue since you've reinstalled Alienfx and rebooted?

**Comment by aemaem** [comment]
I also have the same error. It's getting stuck during "Applying Theme".

This is the log when trying to apply via commandline: `alienfx --log /tmp/alienfx.log --theme default`
```
DEBUG:root:USB device acquired, VID=0x187c, PID=0x530
DEBUG:root:SENDING: GET_STATUS
ERROR:root:read_packet: [Errno 75] Overflow
DEBUG:root:SENDING: RESET: all-lights-on
ERROR:root:write_packet: [Errno 32] Pipe error
DEBUG:root:SENDING: GET_STATUS
ERROR:root:read_packet: [Errno 75] Overflow
DEBUG:root:USB device released, VID=0x187c, PID=0x530
ERROR:root:'NoneType' object is not subscriptable
```

**Comment by wanjizheng** [comment]
same issue here.  Won't apply the theme

**Comment by derco0n** [comment]
Seems there are new controllers in some models which are using 8 instead of 4 bit per color.

i'm currently working on support for model 17R4. for that purpose i created a newcmdpacket.py with modified properties for newer alienfx-controllers. it is still under development, but you might have a look at my fork: https://github.com/derco0n/alienfx

**Comment by glmaljkovich** [comment]
I have a 15R3 and this works great out of the box. Not sure if this issue is relevant anymore.

My setup:
- alienfx 2.3.4
- Kubuntu 18.04
- python 2.7
