### ISSUE TITLE
15R2 Syntax Error

### ISSUE THREAD

**Issue by foxsae** [trackmastersteve/alienfx#32]
Just tried to install on my Ubuntu 17.10 Alienware 15R2 and I was greeted with this error:
Perhaps this is a system configuration issue, but I followed the instructions. 

 $ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    import ez_setup
  File "/home/alex/Development/alienfx/ez_setup.py", line 79
    ), file=sys.stderr)
           ^
SyntaxError: invalid syntax

**Comment by Victor-Villacis** [comment]
I am getting the same syntax error. Does the repo need to be cloned to a specific location? I am using an M14xR1

**Comment by Dutisto** [comment]
Hi guys,
Can you test "python --version" ? I think you're using python3, but the setup.py is written for python 2.7 :)

**Comment by trackmastersteve** [comment]
I've been trying to get this app updated to work with python3. But there is still a lot of work to be done and I'm still learning python myself. I'm happy to accept contributions to the project though! ;)

**Comment by trackmastersteve** [comment]
I have added "pip install future" to the dependencies. Let me know if this fixes the syntax error.

**Comment by hotternative** [comment]
I am having the same issue with Ubuntu 16.04 on 15R3. Python version is 2.7.12.

$ sudo python2 setup.py install
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    import ez_setup
  File "/home/don/alienfx/ez_setup.py", line 79
    ), file=sys.stderr)
           ^
SyntaxError: invalid syntax

$ python --version
Python 2.7.12

**Comment by trackmastersteve** [comment]
@hotternative the latest versions of alienfx are written for python3. `$ sudo python3 setup.py install`

**Comment by hotternative** [comment]
@trackmastersteve **Thanks for your reply. I paste here my experience just in case some other person have same issue**

**I first tried**: `$ sudo python3 setup.py install`


$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    import ez_setup
  File "/home/don/alienfx/ez_setup.py", line 17, in <module>
    from future import standard_library
ImportError: No module named 'future'

**So I tried to install setuptools and future.**
$ pip install setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/96/06/c8ee69628191285ddddffb277bd5abdf769166e7a14b867c2a172f0175b1/setuptools-40.4.3-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 1.3MB/s 
Installing collected packages: setuptools
Successfully installed setuptools-20.7.0

$ pip install future
Collecting future
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 1.0MB/s 
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /home/don/.cache/pip/wheels/bf/c9/a3/c538d90ef17cf7823fa51fc701a7a7a910a80f6a405bf15b1a
Successfully built future
Installing collected packages: future
Successfully installed future-0.16.0

**Then I tried again but I got same error..** 
$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    import ez_setup
  File "/home/don/alienfx/ez_setup.py", line 17, in <module>
    from future import standard_library
ImportError: No module named 'future'

**Then I tried:** 
$ sudo python setup.py install
and it seems happy.
...
...
Finished processing dependencies for alienfx==2.3.4

To be honest I don't know why `python` works while `python3` doesn't.

**Comment by trackmastersteve** [comment]
`pip install package` is for python2. And `pip3 install package` is for python3. I hope that helps!

**Comment by KaleabTessera** [comment]
Same issue as @hotternative . Nothing fixed it. This is on python version 3.7.1 and 2.7.16, error:
```
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    import ez_setup
  File "/home/kaleab/Documents/Tests/alienfx/ez_setup.py", line 79
    ), file=sys.stderr)
           ^
SyntaxError: invalid syntax
```
