### ISSUE TITLE
No supported Alien FX controllers found!

### ISSUE THREAD

**Issue by TheOmegaPope** [trackmastersteve/alienfx#34]
I have an Alienware Area51 R2 case (big triangle desktop)

I got the case second hand and other than the cables in it nothing else is stock.

I am really hoping someone is able to help me get AlienFX to see and control my lighting as it is my last hope. Right now the front panel is rimmed in Green and Purple with a light purple button and the sides never turn on at all, with no way to change any of them.

All official versions refuse to recognize my system and install.

Help me trackmastersteve, you're my only hope.

**Comment by trackmastersteve** [comment]
Linux recognizes Alienfx as being a USB device. That means that the controller board is either built in to the original motherboard. Or it might have to be plugged into the motherboard in some way that it is seen as a USB device. To be honest, of all the times I've stripped my Alienware apart, I've never looked for the Alienfx hardware itself. Sorry I couldn't be much help!
