### ISSUE TITLE
I have an M17xR2.. I want to help.

### ISSUE THREAD

**Issue by PadreAdamo** [trackmastersteve/alienfx#35]
I have an M17xR2.. I want to help.

I'm generally a newer Linux user; about 2.5 years now. I have used Ubuntu, OpenSUSE, and Solus. Please let me know what you need to hammer-down support for the M17xR2.

**Comment by trackmastersteve** [comment]
If you're able to code, we love to accept pull requests. But bug reports are also welcome!
