### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by vakaobr** [trackmastersteve/alienfx#37]
### 1. Expected behavior.

- While trying to use the alienfx on a 17R3 (not m17xr3) got a "not controller found"

### 2. Actual behavior.

- I'm able to put the program to work, single changing the produt id, from `self.product_id = 0x0520` to `self.product_id = 0x0528` but dont have sure if the zones are the same on both models

**Comment by trackmastersteve** [comment]
Yes, the m17xR3 is a different model than the 17R3. So the Alienfx codes are different. Please let me know if any of the zone codes are wrong and what they should be so that I can add them to this project. Thanks!

**Comment by trackmastersteve** [comment]
I have added a controller for your Alienware 17R3. Please let me know if you have any issues with it.

**Comment by vakaobr** [comment]
Sorry to "reopen" that, but we need to put the new model on core/prober.py and data/etc/udev/rules.d/10-alienfx.rules also.

If you want you can add me as contributor to project also, I have limited knowledge on python, but I think that could be a nice way to keep learning.

**Comment by trackmastersteve** [comment]
Thank you for pointing that out. I completely forgot to edit those other files. It has now been fixed. You are very welcome to send me PRs so I can review/submit your code to the project.
