### ISSUE TITLE
17R3 - Zone testing

### ISSUE THREAD

**Issue by vakaobr** [trackmastersteve/alienfx#38]
### 1. Expected behavior.

- Zones should act as stated on software

### 2. Actual behavior.

Major problems:

- Right Speaker - Zone missing (LED remains OFF)
- Touchpad - Zone missing (LED remains OFF)

Misplaced zones to that specific model:

- Alien Head Zone - Points to wi-fi / caps-lock / num-lock LED's zone
- Media Bar (maybe this zone on 17R3 should be named "external cover") - Points to Left Speaker zone
- Right Speaker - Points to Alienware name below the display (I think that is the zone named Logo) zone
- Touchpad - Points to HDD LED zone
- Logo - Points to Alien Head zone
- Left speaker - Points to External Display Cover lines

Improvements/suggestions:

- Right keyboard - That zone should be named numerical keyboard
- Middle right keyboard - That zone should be named right keyboard
- Middle left keyboard - That zone should be named center keyboard

**Comment by trackmastersteve** [comment]
If you would like, you can make those edits to [https://github.com/trackmastersteve/alienfx/blob/master/alienfx/core/controller_17r3.py](url) and send me a  Pull Request for review. Or, if you like, I can just make those changes myself.

**Comment by trackmastersteve** [comment]
I have updated these zone codes. Please let me know if they are right.

**Comment by derco0n** [comment]
@vakaobr Please try to use the new zonescanner to determine the correct zones for your device

Personally, i refuse your suggestions to rename the keyboard zones.
You should consider, that not every device has a numericcal keyboard. AFAIK only the 17" devices have one...

**Comment by vakaobr** [comment]
Hello Dennis,

Thanks, I will test it tomorrow morning and let you know.

The suggestion to rename zones it’s to match that specifically to 17”/18” inch models only.

Regards,

Anderson 

Enviado do meu iPhone

Em 10 de ago de 2018, à(s) 18:46, Dennis Marx <notifications@github.com> escreveu:
