### ISSUE TITLE
17R4 GUI hangs when trying to apply theme CLI ok

### ISSUE THREAD

**Issue by billythakidd04** [trackmastersteve/alienfx#45]
### 1. Expected behavior.

- Apply loaded theme when clicking the :heavy_check_mark:  

### 2. Actual behavior.

- GUI hangs with 'Applying Theme' messge. I've let this sit for over 3 hours with no change.
![screenshot from 2018-07-28 03-41-57](https://user-images.githubusercontent.com/888231/43354367-13bf859e-9219-11e8-91cb-45a695fb9b64.png)

### 3. Steps to reproduce the problem.

- Open the AlienFX GUI and try to apply any theme. I have not tested the power zone, this is only relating to the 'Normal Zones' at the moment.

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version: 2.2.0
- Operating System: Ubuntu 18.04
- Hardware Version: 17 r4

### 5. Additional info.

- The CLI command works immediately.

**Comment by trackmastersteve** [comment]
Have you tried creating your own theme and applying it?

**Comment by billythakidd04** [comment]
Yes I created a custom theme both through the UI (which works perfectly
applying on the cli) and through json.

**Comment by trackmastersteve** [comment]
@derco0n Do you have any idea of what would be causing this bug?

**Comment by derco0n** [comment]
@trackmastersteve not at the moment, sorry. i'm not at home the next week, i'll try to check and repair that in the following week.

**Comment by billythakidd04** [comment]
@derco0n Is there something I can do to test?

``` shell
alienware:~$ dpkg -l | egrep "libgtk-?[[:digit:]].*:amd[[:digit:]]{2}"
ii  libgtk-3-0:amd64                           3.22.30-1ubuntu1                    amd64        GTK+ graphical user interface library
ii  libgtk2.0-0:amd64                          2.24.32-1ubuntu1                    amd64        GTK+ graphical user interface library
```

**Comment by trackmastersteve** [comment]
@billythakidd04 can you try copying the `10-alienfx.rules` file from `/etc/udev/rules.d/` to `/lib/udev/rules.d/` and see if that helps? I remember I had to do that once before. But I can't remember if that was Ubuntu or not.

**Comment by billythakidd04** [comment]
Sure, I'll report back tomorrow

**Comment by billythakidd04** [comment]
@trackmastersteve that works brilliantly.

**Comment by trackmastersteve** [comment]
Glad it worked!
