### ISSUE TITLE
17r4 GUI Left and Right display zones cannot be assigned?

### ISSUE THREAD

**Issue by billythakidd04** [trackmastersteve/alienfx#46]
### 1. Expected behavior.
![screenshot from 2018-07-29 21-23-15](https://user-images.githubusercontent.com/888231/43373195-12e67f3e-9376-11e8-87ab-ad39c66a9042.png)

- Click on the zone to assign a new color to.
- Select the color you want.
- Save and apply theme.

### 2. Actual behavior.

- Plus symbol is "ghosted"

### 3. Steps to reproduce the problem.

- see above

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version: 2.2.0
- Operating System: ubuntu 18.04
- Hardware Version: 17r4

**Comment by derco0n** [comment]
i need to check/test the changes i made within the gtk-gui.
i'll do so.
in the meantime please use CLI-version

**Comment by derco0n** [comment]
Ok.Following situation:
If you have set a theme via commandline before, you are able to change the zonesettings for left and right display, exactly the same way you can do this with the other zones, by simply clicking their colorfield. - if you just click the zonename (text on the left coloumn), the properties are greyed out. - this is normal behaviour for all zones.

BUT: If you create a new theme, the two display-zones are not initialized, therefore you cannot click the colorfield and are unable to change the color...

Cant' be that much....
Hang on

**Comment by derco0n** [comment]
Pull request is out.
The default-theme just needed some values for the two zones...
