### ISSUE TITLE
Create a device list

### ISSUE THREAD

**Issue by derco0n** [trackmastersteve/alienfx#50]
The device-controller-naming is a bit irritating, as the controller-naming differs from what the bios is telling me: e.g.  M17R4<->Alienware 17 R4

Therefore i suggest to create a device-list which should contain the following information:

-Name in alienfx (controller_<device>.py)
-devicename as shown in bios (or windows commandline via "wmic computersystem get model")
-device release date
-controllers hardware ID
-optionally a picture

**Comment by derco0n** [comment]
created a devicelist. pull request is open.
if it will be accepted, please contribute to that list.
Thank you in advance

**Comment by trackmastersteve** [comment]
Accepted the Pull request. Thank you @derco0n.
