### ISSUE TITLE
Alienfx CLI instructions

### ISSUE THREAD

**Issue by ntej** [trackmastersteve/alienfx#51]
@trackmastersteve where can I find the information on how to use the CLI? Can't find any alienFX main page as mentioned in instructions

**Comment by trackmastersteve** [comment]
you can run `$ alienfx --help` or just `$ alienfx -h` to see all the commands you can run from the CLI.

**Comment by trackmastersteve** [comment]
you can also run `$ man alienfx` to see the man page for it.

**Comment by ntej** [comment]
@trackmastersteve thank you. Mine is Alienware 15 R3 running Ubuntu 18.04.1 LTS. When I try to set colors using GUI program it's not working but  CLI program is working fine for all except trackpad.

**Comment by trackmastersteve** [comment]
Have you tried creating a controller file `alienfx/core/controller_m15xr3.py` with the correct zone codes for your zones? Please see [CONTRIBUTING.md](https://github.com/trackmastersteve/alienfx/blob/master/CONTRIBUTING.md) for instructions on how to do so. I don't currently see one in the list. So if you are able to create one that works, please submit a pull request and I'll be happy to add it.

**Comment by ntej** [comment]
@trackmastersteve for sure, I will try it and raise a pull request if it works!
