### ISSUE TITLE
Alienware Aurora R7 - No USB Controller

### ISSUE THREAD

**Issue by poldon** [trackmastersteve/alienfx#55]
### 1. Expected behavior.

-Running alienfx should find the Aurora R7.

### 2. Actual behavior.

> You are running alienfx under Python-Version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
> [GCC 7.3.0]
> ERROR:root:No Alien FX controller, defined by a supported model, found!
> would you like to perform a zonescan? (y/n):y
> Performing zonescan...
> Welcome. This will help you to scan for alienfx-controllers and their lightning zones.
> Traceback (most recent call last):
>   File "/usr/local/bin/alienfx", line 11, in <module>
>     load_entry_point('alienfx==2.3.4', 'console_scripts', 'alienfx')()
>   File "build/bdist.linux-x86_64/egg/alienfx/ui/console/main.py", line 72, in start
>   File "build/bdist.linux-x86_64/egg/alienfx/core/zonescanner.py", line 139, in scan
> TypeError: 'NoneType' object is not iterable
> 

If I run lsusb on the Aurora, it looks like there isn't a USB controller for it:

> Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 001 Device 003: ID 0cf3:e301 Atheros Communications, Inc. 
> Bus 001 Device 002: ID 0764:0501 Cyber Power System, Inc. CP1500 AVR UPS
> Bus 001 Device 005: ID 04ca:0027 Lite-On Technology Corp. 
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> 

### 3. Steps to reproduce the problem.

-Run alienfx on an Aurora R7.

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version: 2.3.4
- Operating System: Ubuntu 18.04
- Hardware Version: Aurora R7

Hopefully, there's a simple fix, but I just haven't found it yet.

**Comment by DenDeze** [comment]
strange, are you sure thet it should be a usb controller? i have the laptop15R4 wich is not supported yet but my controller at least is showing in lsusb... what is your linux version?

**Comment by knair97** [comment]
I am having the same issue on 19.10 with an Aurora R7. 

Currently, I am running a dual boot so I am able to boot into Windows to change the color which persists when I boot into Linux.

**Comment by trackmastersteve** [comment]
I noticed you are running it in python2. This app doesn't support python2 since alienfx version 2.1+ . Try installing/running it with python3.

**Comment by Ocean572** [comment]
I am having the exact same problem. It doesnt show up in lsusb.

**Comment by queengooborg** [comment]
I'm running into the same issue as well.  I'm running Python 3.12, so it isn't an issue running on Python 2.  Logging output is the following (which is almost an identical match to the reporter's log):

```
You are running alienfx under Python-Version: 3.12.3 (main, Nov  6 2025, 13:44:16) [GCC 13.3.0]
ERROR:root:No Alien FX controller, defined by a supported model, found!
would you like to perform a zonescan? (y/n):y
Performing zonescan...
Welcome. This will help you to scan for alienfx-controllers and their lighting zones.
Traceback (most recent call last):
  File "/usr/local/bin/alienfx", line 33, in <module>
    sys.exit(load_entry_point('alienfx==2.4.3', 'console_scripts', 'alienfx')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/alienfx-2.4.3-py3.12.egg/alienfx/ui/console/main.py", line 81, in start
  File "/usr/local/lib/python3.12/dist-packages/alienfx-2.4.3-py3.12.egg/alienfx/ui/console/main.py", line 64, in doZonescan
  File "/usr/local/lib/python3.12/dist-packages/alienfx-2.4.3-py3.12.egg/alienfx/core/zonescanner.py", line 134, in scan
TypeError: 'NoneType' object is not iterable
```

`lsusb` doesn't show a controller either:

```
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0cf3:e009 Qualcomm Atheros Communications 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 214b:7250 Huasheng Electronics USB2.0 HUB
Bus 003 Device 003: ID 0000:3825   USB OPTICAL MOUSE
Bus 003 Device 004: ID 04f2:0841 Chicony Electronics Co., Ltd HP Multimedia Keyboard
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
```

After doing some more research, it appears that this is because the [R6 and R7 use ACPI to control the lights rather than USB](https://github.com/trackmastersteve/alienfx/issues/97#issuecomment-1008551436).
