### ISSUE TITLE
Want to Help Add Support for the Alienware Alpha Model

### ISSUE THREAD

**Issue by VampireFox2** [trackmastersteve/alienfx#59]
Hi,

I'm really amazed at all these different projects supporting AlienFx on different models. I wasn't expecting to find anything to replace the Alienware Command Center. So hats off to you guys for developing this. I have an Alienware Alpha R1 along with the Tactx keyboard and mouse that I bought in 2015 and I haven't seen anyone support this model yet. I currently have Fedora 29 on it. I can't stand Windows anymore. I see that this project is written in Python. I'm okay with Python, I'm still learning though. I would like to help out with adding support for this model however way I can do so. I don't know really anything about how the BIOS, the hardware etc. communicates with AlienFx. So if possible could you point me in the right direction for information on this? That would be awesome. Anyways thank you for your time and keep up the good work.

**Comment by trackmastersteve** [comment]
Thank you @VampireFox2 for your interest in contributing to our project. The AlienFX chip is seen as a "USB device" on the motherboard. This software controls that USB device using udev rules on Linux. Feel free to take a look at some of the controller files for other models. The steps to adding support for your model are in [CONTRIBUTING](https://github.com/trackmastersteve/alienfx/blob/master/CONTRIBUTING.md).

Thanks again and good luck!
