### ISSUE TITLE
Alienware 13R2 issue with applying theme

### ISSUE THREAD

**Issue by Magikro** [trackmastersteve/alienfx#62]
I have the same issue that others have had previously- the application just sits on applying theme and never actually changes the light color. Has there been a fix for this somewhere? I am using an alienware 13r2 and I followed the guide for installing the program with sudo.

**Comment by Magikro** [comment]
To add, I have the same issue that issue #57 has, but there really wasn't an answer to that problem.

**Comment by Magikro** [comment]
Also to add, the CLI does work, just not the GUI

**Comment by syreal17** [comment]
Ditto.
