### ISSUE TITLE
alienware m17x I/O operation on closed file

### ISSUE THREAD

**Issue by ghost** [trackmastersteve/alienfx#64]
### 1. Expected behavior.

- I thinm M17x is included as a supported device, but it asks for a zone scan anyways

### 2. Actual behavior.

- zone scan fialed, details below:

ERROR:root:No Alien FX controller, defined by a supported model, found!
would you like to perform a zonescan? (y/n):y
Zonescan might not run correctly under Python 2.If you experience issues, try running under Python 3 instead.
Performing zonescan...
Welcome. This will help you to scan for alienfx-controllers and their lightning zones.
Found device "0x187c / 0x0524". - Testing zones...
Testing zone "0x0001"
ERROR:root:Cant detach kernel driver. Error : Access denied (insufficient permissions)
ERROR:root:Cant set configuration. Error : Access denied (insufficient permissions)
ERROR:root:Cant claim interface. Error : Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:Controller status could not be retrieved. Is the device already in use?
ERROR:root:Error while testing current zone...
ERROR:root:Cant re-attach. Error : Access denied (insufficient permissions)
is anything blinking now? (y/n):Traceback (most recent call last):
  File "/usr/local/bin/alienfx", line 11, in <module>
    load_entry_point('alienfx==2.3.4', 'console_scripts', 'alienfx')()
  File "build/bdist.linux-x86_64/egg/alienfx/ui/console/main.py", line 81, in start
  File "build/bdist.linux-x86_64/egg/alienfx/ui/console/main.py", line 64, in doZonescan
  File "build/bdist.linux-x86_64/egg/alienfx/core/zonescanner.py", line 148, in scan
  File "build/bdist.linux-x86_64/egg/alienfx/core/zonescanner.py", line 131, in scanzone
  File "build/bdist.linux-x86_64/egg/alienfx/core/zonescanner.py", line 53, in askuser
ValueError: I/O operation on closed file

### 3. Steps to reproduce the problem.

- I strictly followed the instructions except for one step. 
When i use "pip install future", I keep on running into the problem of "ImportError: No module named builtins", so I used "sudo pip install future" instead. Then when I alienfx, the software can run. 

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version:
- Operating System: ubuntu 18.04
- Hardware Version: alienware m17x (2013)

**Comment by linux-devil** [comment]
Use sudo and check

**Comment by student020341** [comment]
Hey, I have this issue on my machine now. When I use sudo or move the themes into a folder that has open permissions, the terminal says:
```
tom@pop-os:/opt/foo$ sudo XDG_CONFIG_HOME=/opt/foo  alienfx -t default
You are running alienfx under Python-Version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
ERROR:root:'_Environ' object is not callable
ERROR:root:'AlienFXThemeFile' object has no attribute '_theme_dir' 
```

I get similar output for trying to list themes as well. /opt/foo has 777 permissions and contains a folder named alienfx that has all of the themes. 
```
tom@pop-os:/opt/foo/alienfx$ pwd
/opt/foo/alienfx
tom@pop-os:/opt/foo/alienfx$ ls -1
17r4_allblue.json
17r4_allgreen.json
17r4_allred.json
17r4_dark.json
17r4_derco0n_green-red.json
17r4_flag_fr.json
17r4_flag_ge.json
17r4_flag_it.json
17r4_flag_us.json
17r4_HotPursuit.json
Arch.json
BlueWhite.json
dark.json
default.json
m14xr2_dark.json
m14xr2_default.json
PhilippineFlag.json
RedWhiteBlue.json
ubuntu.json
```

Do I have the folder structure wrong? I am able to list the contents
```
tom@pop-os:~/.config/alienfx$ alienfx -s
You are running alienfx under Python-Version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
Available themes:
	17r4_HotPursuit
	17r4_allblue
	17r4_allgreen
	17r4_allred
	17r4_dark
	17r4_derco0n_green-red
	17r4_flag_fr
	17r4_flag_ge
	17r4_flag_it
	17r4_flag_us
	Arch
	BlueWhite
	PhilippineFlag
	RedWhiteBlue
	dark
	default
	m14xr2_dark
	m14xr2_default
	ubuntu
```

but attempting to set one yields an error like this issue.  
```
tom@pop-os:~/.config/alienfx$ alienfx -t default
You are running alienfx under Python-Version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
ERROR:root:Cant detach kernel driver. Error : Access denied (insufficient permissions)
ERROR:root:Cant set configuration. Error : Access denied (insufficient permissions)
ERROR:root:Cant claim interface. Error : Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:write_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:read_packet: [Errno 13] Access denied (insufficient permissions)
ERROR:root:Controller status could not be retrieved. Is the device already in use?
ERROR:root:Cant re-attach. Error : Access denied (insufficient permissions)
```
