### ISSUE TITLE
Aurora R3 - No controller

### ISSUE THREAD

**Issue by gastrodon** [trackmastersteve/alienfx#65]
### 1. Expected behavior.
Should find my hardware

### 2. Actual behavior.
`No supported Alien FX controller found!`
![image](https://user-images.githubusercontent.com/10934565/59546022-89b54200-8ef5-11e9-9a14-afa8b0cb50ad.png)

### 3. Steps to reproduce the problem.
Install and run the created desktop file AlienFX

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version: Looks like `2.3.4`
- Operating System: `uname -a` returns `Linux alien 5.1.6-arch1-1-ARCH #1 SMP PREEMPT Fri May 31 15:17:53 UTC 2019 x86_64 GNU/Linux`
- Hardware Version: Alienware Aurora R3

Is the Aurora R3 unsupported as of yet?

**Comment by AbhijeetKrishnan** [comment]
You can test it using the zonescan feature. Run `sudo alienfx -z` to start zonescan and identify which zones are powered by which codes on your device. You can then write your own controller in Python following the template of the existing controllers.
