### ISSUE TITLE
Alienware 15 R4

### ISSUE THREAD

**Issue by ZenSvelte** [trackmastersteve/alienfx#70]
### 1. Expected behavior.

- Working lights

### 2. Actual behavior.

- The lights are not working no matter what I do

I'm a bit confused by what is going on here, but it seems to me that you've figured out a way to control the Alienware lights outside of the command center. I'm unfamiliar with programming and Git, so I'm not sure how to use any of the items on your page. Could you lend me a hand so I can try to get my lights working again? I would greatly appreciate it. I use an Alienware 15 R4. Also apologies for not exactly following the issue template

- Project Version:
- Operating System: Windows 10 Pro
- Hardware Version:

**Comment by Steampunkery** [comment]
I'm not in any way related to this project other than a user, but this is a Linux controller. It'll only work on Linux operating systems.

**Comment by trackmastersteve** [comment]
Thank you @Steampunkery. Yes, this is only for Linux.
