### ISSUE TITLE
How do I find the values for an M17R2-2019?  

### ISSUE THREAD

**Issue by RobertLHarris** [trackmastersteve/alienfx#72]
### 1. Expected behavior.

I read the Contributing Doc, there's no instructions on how to pull the actual values.  I'm running Linux and can run dmideoce in addition to lshw or anything else if given instructions.

**Comment by zenbiking** [comment]
@RobertLHarris - install the software as is, and then run "alienfx -z" at the command prompt. Follow the prompts and it will give you the values

**Comment by trackmastersteve** [comment]
Thank you @RobertLHarris
