### ISSUE TITLE
No module named 'future' but I installed the package via pip.

### ISSUE THREAD

**Issue by zk-tux** [trackmastersteve/alienfx#73]
### 1. Expected behavior.

-

### 2. Actual behavior.

-

### 3. Steps to reproduce the problem.

-

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version:
- Operating System:
- Hardware Version:

**Comment by zk-tux** [comment]
*EDIT: solved this by running pip3 install future if anyone runs into this.

**Comment by trackmastersteve** [comment]
Thank you for the follow up @zk-tux
