### ISSUE TITLE
No Available themes and not sure how to use GUI

### ISSUE THREAD

**Issue by rishanshah** [trackmastersteve/alienfx#76]
### 1. Expected behavior.
I type in alienfx -s pick a theme and set it with alienfx -t

I tried to download some xml themes from online for alienware

None of them worked. How can I set the themes or use the gui?

- Operating System: Ubuntu 20.04

**Comment by wandrewp** [comment]
You send it the .json file name from alienfx/alienfx/data/themes/ with the -t flag.  I think after you install it you should have default.json in your $HOME/.config/alienfx/ folder.

Try the default.json.  What's your Alienware model?
