### ISSUE TITLE
ez_setup.py Cannot find Module setuptools.py and future.py. (Even though I installed them)

### ISSUE THREAD

**Issue by spkouma** [trackmastersteve/alienfx#80]
### 1. Expected behavior.
Installing setup.py 
-

### 2. Actual behavior.
ez_setup.py Cannot find Module setuptools.py and future.py. (Even though I installed them)
-

### 3. Steps to reproduce the problem.

-

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version:
- Operating System:
- Hardware Version:

**Comment by Slagr618** [comment]
Use pip3 instead.

**Comment by trackmastersteve** [comment]
Try using pip3 to install setuptools and future. That should fix it.
