### ISSUE TITLE
DNF Error: Unable to find a match: pygobject3

### ISSUE THREAD

**Issue by WillNilges** [trackmastersteve/alienfx#88]
### 1. Expected behavior.

- Installing Fedora dependencies completes successfully

### 2. Actual behavior.

```
(py36) [wilnil@devbox01 alienfx]$ sudo dnf -y install pygobject3
Last metadata expiration check: 2:47:18 ago on Sun 17 Jan 2021 07:47:35 AM EST.
No match for argument: pygobject3
Error: Unable to find a match: pygobject3
```

### 3. Steps to reproduce the problem.

- Attempt to install the `pygobject3` package, which does not exist.

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version: 6ec9d31c5687626167cbc9680c65b0505f4de873
- Operating System: Fedora 33
- Hardware Version: Alienware Aurora R4

**Comment by WillNilges** [comment]
This is the correct package:
```
sudo dnf -y install python3-gobject
```

Please update the README!

**Comment by trackmastersteve** [comment]
Thanks for the info. I have updated the README. Feel free to just send a Pull Request next time.
