### ISSUE TITLE
13r3 permissions error

### ISSUE THREAD

**Issue by backpack5689** [trackmastersteve/alienfx#89]
### 1. Expected behavior.
Should change the color theme.
-

### 2. Actual behavior.
`ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:write_packet: [Errno 32] Pipe error
ERROR:root:read_packet: [Errno 75] Overflow
ERROR:root:Controller status could not be retrieved. Is the device already in use?
`
-

### 3. Steps to reproduce the problem.
Attempt to change the color theme on a Alienware 13r3 either using the alienfx or alienfx-gtk version (either with or without sudo)
-

### 4. Specifications like the version of the project, install method, operating system, and hardware.

- Project Version: Project as of January 19th, 2021
- Operating System: Linux Mint
- Hardware Version: Alienware 13r3

**Comment by YoannMourot** [comment]
That is not a permission error, just the new usb controller for new alienwares (post ~2015) that seems to want 8 bits colors instead of 4 as mentionned by @derco0n. This must have been solved for the Alienware 13r3 in the last commit, give it a shot :)
