### ISSUE TITLE
Remove alienfx from Linux Mint 20

### ISSUE THREAD

**Issue by WildWeasel109** [trackmastersteve/alienfx#92]
Hi,
Can you advise on how to fully remove alienfx once installed. I'm getting an error on execution and want to fully reinstall.

Thanks

Ian

**Comment by WildWeasel109** [comment]
I've actually removed all alienfx files from /usr/local/bin and ~/.local/bin. Scanned drives and cannot seen anymore files, have I missed any?

**Comment by trackmastersteve** [comment]
Have you removed the udev rules loated in /etc/udev/rules.d/ ?

**Comment by trackmastersteve** [comment]
A reinstall will overwrite all of the files. But if you just want to uninstall it, this is where you can find these files:

/usr/share/applications <-- alienfx/data/share/applications/alienfx.desktop
/usr/share/icons/hicolor/scalable/apps <-- alienfx/data/icons/hicolor/scalable/apps/alienfx.svg
/usr/share/icons/hicolor/48x48/apps <-- alienfx/data/icons/hicolor/48x48/apps/alienfx.png
/usr/share/pixmaps <-- alienfx/data/pixmaps/alienfx.png
/usr/share/man/man1 <-- docs/man/alienfx.1

**Comment by WildWeasel109** [comment]
Interesting, it seems you've fixed the issue I was having and when I reinstalled I was able to change colours.

Thanks

Ian

**Comment by trackmastersteve** [comment]
No Problem

**Comment by V1K1NGbg** [comment]
@trackmastersteve I tried the method above on my pop os machine,, but I couldn't make it dissapear ffrom the app launcher. Can you plese provide more detailed instructions for deinstalation

Thank you in advance!
