### ISSUE TITLE
question: windows support?

### ISSUE THREAD

**Issue by raould** [trackmastersteve/alienfx#97]
hi, the AWCC on e.g. Aurora R7 is lame because it can't do dynamic effects ie "breathing" so I am looking for something better, and/or scriptable. Yes I am stuck on Windows 10 for now. Wondering if anybody has considered what it might take to port this all to run on Windows? I didn't notice it mentioned when searching in this repo or online, apologies if this is some very old-hat question to bring up.

**Comment by now0clock** [comment]
Try doing what I did on an AW 17 R3. Delete the entire windows partition(s) and format the disk (after saving a backup disk image of course.) Or just replace the disk WIN10 is on with a blank disk. Install Debian, or a Debian based Linux distro like Ubuntu or Mint. You can try them out on bootable USB flash drives to get a feel for them and test them out. (YMMV.) If you need to, you can install WINE or have a Virtual box in Linux. I don't see a reason to ever go back to a closed source, proprietary operating system again. It's pretty nice to actually own your own computer. Just my experience. good luck! :)

**Comment by kindrowboat** [comment]
@raould maybe check out T-Troll/alienfx-tools for Windows.

**Comment by T-Troll** [comment]
Yes, Aurora R7 is supported.
BTW, only R7 and R6 uses ACPI controlled lights, not USB-controlled like others.
